#!/bin/sh
# Generated by sb90-deploy — the same file ships as install.sh, update.sh and
# link-hive.sh; it runs `bootstrap.py <its own name>`. Its only job is finding a
# Python 3.6+ to start with; bootstrap.py takes it from there.
here="$(cd "$(dirname "$0")" && pwd)"
command="$(basename "$0" .sh)"
for py in python3 python; do
    if command -v "$py" >/dev/null 2>&1 \
        && "$py" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)' 2>/dev/null; then
        exec "$py" "$here/bootstrap.py" "$command" "$@"
    fi
done
echo "[ERROR] Python 3.6+ is required to run $command, and none was found." >&2
echo "        On Debian/Ubuntu: sudo apt install python3 python3-venv" >&2
exit 1
