# Generated by sb90-deploy - the same file ships as install.ps1, update.ps1 and
# link-hive.ps1; it runs `bootstrap.py <its own name>`. Its only job is finding
# a Python 3.6+ to start with; bootstrap.py takes it from there.
#Requires -Version 5.1
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$command = [IO.Path]::GetFileNameWithoutExtension($MyInvocation.MyCommand.Path)
$check = 'import sys; sys.exit(0 if sys.version_info >= (3, 6) else 1)'
foreach ($candidate in @(@('py', '-3'), @('python'), @('python3'))) {
    $exe = $candidate[0]
    $pre = @($candidate | Select-Object -Skip 1)
    if (-not (Get-Command $exe -ErrorAction SilentlyContinue)) { continue }
    # The Microsoft Store 'python' alias exists but fails this check - skip it.
    & $exe @pre -c $check 2>$null
    if ($LASTEXITCODE -ne 0) { continue }
    & $exe @pre (Join-Path $here 'bootstrap.py') $command @args
    exit $LASTEXITCODE
}
Write-Host "[ERROR] Python 3.6+ is required to run $command, and none was found." -ForegroundColor Red
Write-Host "        Install Python from https://python.org (tick 'Add to PATH') and re-run."
exit 1
